### ISSUE TITLE
how do i start this program?

### ISSUE THREAD

**Issue by GitGudJuno** [neuro-sys/tumblr-downloader-client#22]
Can you provide a step by step to start using this function?

**Comment by neuro-sys** [comment]
@GitGudJuno Hello, what is your computer's operating system?

**Comment by neuro-sys** [comment]
Depending on your operating system, you download the application from this page:

https://github.com/neuro-sys/tumblr-downloader-client/releases/tag/v1.0

After that, you should be able to start the application by double clicking with your mouse on the executable file.

Next thing you need to do is to go to the web page: https://www.tumblr.com/oauth/apps, log in, and click Register Application button.

There you fill the form as follows:

Input | Value
-- | --
Application Name | GitGudJuno Tumblr Downloader
**Application Website** | http://localhost/tumblr
Application Description |  My Tumblr Downloader.
Administrative contact email | your email address
**Default callback URL** | http://localhost/tumblr/callback

**Bold** fields are very important, and others are not.

You click register and you should see something similar to this:

![untitled](https://cloud.githubusercontent.com/assets/648622/24583000/d11bb8e2-1745-11e7-9f87-4b03bd8bd058.png)


You need to copy and paste **OAuth Consumer Key** and **Secret Key** fields into Tumblr Downloader application. The rest should be easy to follow, I hope.

**Comment by R-L-T-Y** [comment]
I wonder how do we bypass the API limit of Tumblr...
