### ISSUE TITLE
Starting Error

### ISSUE THREAD

**Issue by Pillow-Fan** [neuro-sys/tumblr-downloader-client#23]
I've configured everything as requested (blog name, consumer key and consumer secret) but after clicking download it freezes at "*Starting...". Right now this is the easiest way but i can't make it work. Help please.
![screenshot 40 _li](https://cloud.githubusercontent.com/assets/28104347/25487963/087348a8-2b66-11e7-90f1-0405e55fb18a.jpg)

**Comment by neuro-sys** [comment]
@Pillow-Fan Can you make sure you set "Application Website" and "Default Callback URL" correctly on tumblr apps page?

**Comment by Pillow-Fan** [comment]
I just checked and the "Application Website" and the "Default Callback URL" were right. I also checked the consumer key and the consumer key as well as the blog name and password but they were both right. It still is stuck on "*Starting...". Could it be because I have more then 25.000 liked posts on Tumblr?

**Comment by Pillow-Fan** [comment]
@neuro-sys forgot to mention you on the previous comment

**Comment by neuro-sys** [comment]
@Pillow-Fan Can you tell me what is your OS and whether it's an 32-bit or 64-bit one?

I guess for Windows, I've provided precompiled binaries only for 64-bit, in which case 32-bit wouldn't work.

travis-ci does not support windows builds, so I need to find some service that provides windows builds for both architectures.

But I'll improve error logging, thanks for reporting this.
