### ISSUE TITLE
v1.3 won't start on mac

### ISSUE THREAD

**Issue by blistex** [neuro-sys/tumblr-downloader-client#26]
Hi,

v1.0 works like normal but v1.3 won't even start! I need that video support! This is what my mac says...

`
Process:               tumblr-downloader-gui [668]
Path:                  /Volumes/VOLUME/*/tumblr-downloader-gui.app/Contents/MacOS/tumblr-downloader-gui
Identifier:            test.tumblr-downloader-gui
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           tumblr-downloader-gui [668]
User ID:               501

Date/Time:             2017-07-06 18:36:52.140 +0200
OS Version:            Mac OS X 10.12.5 (16F73)
Report Version:        12
Anonymous UUID:        A98AB7A1-C9C4-BDAB-134E-6CD68F9A2528

Time Awake Since Boot: 760 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/qt/5.9.0/lib/QtGui.framework/Versions/5/QtGui
  Referenced from: /private/var/folders/b_/62c5nh_d4x70x49d5xr4f43w0000gn/T/AppTranslocation/21C9BCC9-2137-46F4-8A27-350487376A9B/d/tumblr-downloader-gui.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Reason: image not found

Binary Images:
       0x101c91000 -        0x1024caffb +test.tumblr-downloader-gui (0) <7168742C-29AA-3041-8067-A7AADA51AAC4> /var/folders/*/tumblr-downloader-gui.app/Contents/MacOS/tumblr-downloader-gui
       0x1024d3000 -        0x102938ff3 +org.qt-project.QtWidgets (5.9 - 5.9.0) <AE4AA969-59ED-3710-9599-34A0CDBB24FB> /var/folders/*/tumblr-downloader-gui.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x102a96000 -        0x102e91feb +org.qt-project.QtGui (5.9 - 5.9.0) <CB0B41E5-77A4-3C96-89F1-6E313FB36616> /var/folders/*/tumblr-downloader-gui.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x102f8b000 -        0x103463ff7 +org.qt-project.QtCore (5.9 - 5.9.0) <26191310-8088-3241-AF40-00D6B96AA623> /var/folders/*/tumblr-downloader-gui.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x10befc000 -        0x10bf39dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff8c0a4000 -     0x7fff8c0a8ffb  com.apple.agl (3.3.1 - AGL-3.3.1) <752FDB92-EF67-3D04-BF40-A352BF1075CF> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff912da000 -     0x7fff912dffff  com.apple.DiskArbitration (2.7 - 2.7) <8AC72143-D3C4-3AA6-84DF-734E3AFAC49B> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff919d8000 -     0x7fff91a6eff7  com.apple.framework.IOKit (2.0.2 - 1324.60.3) <7CE4C98B-107C-3AAA-B49A-F2ACFCBBF526> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff94c06000 -     0x7fff94c14fff  com.apple.opengl (14.0.16 - 14.0.16) <27E7D76E-A26B-39F8-8CF2-AB57920776A3> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fffa3ff3000 -     0x7fffa3ff4ffb  libSystem.B.dylib (1238.60.2) <FC9E9F13-3B18-305C-BE0A-97C7843652B0> /usr/lib/libSystem.B.dylib
    0x7fffa41a6000 -     0x7fffa41fcff7  libc++.1.dylib (307.5) <0B43BB5D-E6EB-3464-8DE9-B41AC8ED9D1C> /usr/lib/libc++.1.dylib

**Comment by neuro-sys** [comment]
@blistex I've just released v1.4, and tested it on OSX, and it should work.

Thanks for reporting this.

**Comment by blistex** [comment]
cok sagol kardesim süpersin vallah! aklina basina saglik cok ise yarar bir uygulama olmus.
