### ISSUE TITLE
v1.3 won't open on macOS Sierra 10.12.5

### ISSUE THREAD

**Issue by mikitaki** [neuro-sys/tumblr-downloader-client#27]
v1.3 won't open on macOS Sierra 10.12.5

**Comment by R-L-T-Y** [comment]
qt5-qtscript @5.8.0_0 fails to build on macOS 10.13
I guess we should wait for the stable release for solution

**Comment by neuro-sys** [comment]
@mikitaki Please check https://github.com/neuro-sys/tumblr-downloader-client/issues/26#issuecomment-317346629

Thanks for reporting.
