### ISSUE TITLE
Tool not working anymore

### ISSUE THREAD

**Issue by vh133** [neuro-sys/tumblr-downloader-client#32]
Is it possible, that Tumblr change something? As I mentioned in issue #28, the downloader stopped after following log-entries:
* Starting...
Initializing environment...
done
Authorizing on tumblr...
* Finished...
I tested it an a Mac as well as on a Linux machine...

Someone have an idea?

**Comment by st-korn** [comment]
I tried today: everything works as before.

**Comment by neuro-sys** [comment]
@vh133 New version here: https://github.com/neuro-sys/tumblr-downloader-client/releases/tag/0.0.1
